sudo: required
services:
  - docker
language: python
python: 2.7
env:
  - TOX_ENV=py_func_v4
  - TOX_ENV=cli_func_v4
install:
  - pip install tox
before_script:
  ## Spin up container
  - cd tools/
  - docker-compose -f docker-compose.test.yml up -d
  - sleep 260
  - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')
  - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'printf "%q" "${GITLAB_URL}"')
  - echo $GITLAB_URL
  - echo $PERSONAL_ACCESS_TOKEN
script:
  - tox -e $TOX_ENV
