sudo: required
dist: xenial
services:
  - docker
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7
language: python
python: 3.7
env:
  - TOX_ENV=py_func_v4
  - TOX_ENV=cli_func_v4
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
